---
apiVersion: v2
actions:
  - name: "Run alpine image to say hello world"
    events:
      - name: "sh.keptn.event.sayhello.triggered"
    tasks:
      - name: "Say Hello World"
        image: "alpine"
        cmd:
          - echo
        args:
          - 'Hello, this is Zero! I am from Team A'
      - name: "Say Hello World Again"
        image: "alpine"
        cmd:
          - echo
        args:
          - 'Hello again!!! this is Zero! I am from Team A'
      - name: "Say Hello World Again"
        image: "ubuntu"
        cmd:
          - echo
        args:
          - 'Hello from Ubuntu!!! Zero from Team A'
      - name: "Run a shell"
        image: "ubuntu"
        cmd:
          - ls
        args:
          - -lah
                
